/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "FINOS DevOps Automation",
  "tagline": "Special Interest Group",
  "url": "https://devops-automation.finos.org",
  "baseUrl": "/",
  "favicon": "img/favicon/favicon-finos.ico",
  "projectName": "FINOS DevOps Automation",
  "organizationName": "FINOS",
  "customFields": {
    "repoUrl": "https://github.com/finos/devops-automation"
  },
  "scripts": [
    "https://buttons.github.io/buttons.js"
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/css?family=Overpass:400,400i,700"
  ],
  "themeConfig": {
    "navbar": {
      "logo": {
        "alt": "FINOS DevOps Automation Logo",
        "src": "img/devops-automation/logo-wht.svg"
      },
      "items": [
        {
          "to": "docs/home",
          "label": "Docs",
          "position": "right"
        },
        {
          "to": "docs/roadmap",
          "label": "Roadmap",
          "position": "right"
        },
        {
          "to": "https://github.com/orgs/finos/teams/devops-automation-maintainers",
          "label": "Team",
          "position": "right"
        },
        {
          "href": "https://github.com/finos/devops-automation",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "copyright": "Copyright © 2023 DevOps Automation - FINOS",
      "logo": {
        "alt": "FINOS Logo",
        "src": "img/favicon/favicon-finos.ico",
        "href": "https://finos.org"
      },
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "docs/home"
            },
            {
              "label": "Roadmap",
              "to": "docs/roadmap"
            },
            {
              "label": "Team",
              "to": "https://github.com/orgs/finos/teams/devops-automation-maintainers"
            },
            {
              "label": "About FINOS",
              "to": "docs/about-finos"
            }
          ]
        },
        {
          "title": "FINOS",
          "items": [
            {
              "label": "FINOS Website",
              "to": "https://www.finos.org/"
            },
            {
              "label": "Community Handbook",
              "to": "https://community.finos.org/"
            },
            {
              "label": "Community Governance",
              "to": "https://community.finos.org/docs/governance/#community-governance"
            }
          ]
        },
        {
          "title": "About FINOS",
          "items": [
            {
              "label": "FINOS Projects on GitHub",
              "to": "https://github.com/finos"
            },
            {
              "label": "Engage the FINOS Community",
              "to": "https://www.finos.org/engage-with-our-community"
            },
            {
              "label": "FINOS News and Events",
              "to": "https://www.finos.org/news-and-events"
            }
          ]
        }
      ],
      "style": "light"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "../docs",
          "editUrl": "https://github.com/finos/open-developer-platform/edit/master/website/",
          "sidebarPath": "/Users/matthewbain/Development/github/devops-automation/website/sidebars.js"
        },
        "theme": {
          "customCss": "/Users/matthewbain/Development/github/devops-automation/website/src/css/custom.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "plugins": [],
  "themes": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
